apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-dashboard.yaml
vars:
- name: NAMESPACE
  objref:
    kind: Secret
    name: kubernetes-dashboard-key-holder
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
